/**
 * OTP provider contract — MAS-21.
 *
 * Defines the abstract surface used by auth flows to deliver one-time
 * passwords to a user's phone number. Concrete providers (Fonnte, Wablas,
 * Twilio, …) live alongside in this directory and implement `OtpProvider`.
 *
 * Design notes:
 *   - Adapters are *delivery* only. OTP generation, storage, expiry, and
 *     verification are owned by the auth module (separate concern).
 *   - All adapters MUST be safe to call from server runtimes only — they
 *     read secrets from process.env via `getEnv()`. Never import from
 *     client components.
 *   - Errors are normalised to `OtpDeliveryError` so callers don't need to
 *     branch on provider-specific failure shapes.
 */

/** Result of a successful OTP delivery. */
export interface OtpSendResult {
  /** Provider-side message id when available (useful for delivery audit). */
  providerMessageId?: string;
  /** Provider key actually used (e.g. "fonnte", "twilio", "null"). */
  provider: string;
  /** Channel the message was sent through. */
  channel: OtpChannel;
}

/** Transport used to deliver the OTP. */
export type OtpChannel = "whatsapp" | "sms";

/** Input passed to `OtpProvider.send`. */
export interface OtpSendInput {
  /** E.164-formatted phone number, e.g. "+628123456789". */
  phone: string;
  /** Numeric or alphanumeric OTP code generated by the caller. */
  code: string;
  /**
   * Pre-rendered human-readable message body. Adapters MUST use this verbatim
   * for non-templated providers (Fonnte/Wablas). Twilio Verify may ignore it
   * and use its own template.
   */
  message: string;
}

/** Provider contract. */
export interface OtpProvider {
  readonly name: string;
  readonly channel: OtpChannel;
  send(input: OtpSendInput): Promise<OtpSendResult>;
}

/** Normalised delivery error. */
export class OtpDeliveryError extends Error {
  readonly provider: string;
  readonly cause?: unknown;
  readonly status?: number;
  constructor(provider: string, message: string, opts?: { cause?: unknown; status?: number }) {
    super(`[otp:${provider}] ${message}`);
    this.name = "OtpDeliveryError";
    this.provider = provider;
    this.cause = opts?.cause;
    this.status = opts?.status;
  }
}

/** Thrown when configuration prevents a provider from being constructed. */
export class OtpConfigurationError extends Error {
  constructor(message: string) {
    super(`[otp:config] ${message}`);
    this.name = "OtpConfigurationError";
  }
}

/**
 * Minimal phone validation — E.164ish.
 *
 * Not a substitute for libphonenumber; rejects only obvious garbage so we
 * don't pay for an outbound API call we know will fail.
 */
export function assertPhone(phone: string): void {
  if (typeof phone !== "string" || phone.trim() === "") {
    throw new OtpDeliveryError("validation", "phone is empty");
  }
  const normalised = phone.trim();
  // Allow "+62..." (E.164) OR "0..." (local Indonesian dial). Reject anything
  // with letters or spaces in the middle.
  if (!/^\+?\d{8,15}$/.test(normalised)) {
    throw new OtpDeliveryError("validation", `phone is not E.164/local digits: "${phone}"`);
  }
}

/**
 * Convert "08xxxxxxx" → "628xxxxxxx" for providers that want digits-only
 * Indonesian format (Fonnte, Wablas). E.164 input ("+628…") is stripped of
 * the leading "+". Already-normalised input passes through.
 */
export function toIndonesianMsisdn(phone: string): string {
  assertPhone(phone);
  const trimmed = phone.trim();
  if (trimmed.startsWith("+")) return trimmed.slice(1);
  if (trimmed.startsWith("0")) return `62${trimmed.slice(1)}`;
  return trimmed;
}
