version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Asia/Jakarta
    open-pull-requests-limit: 5
    labels:
      - "type:chore"
      - "area:devops"
    groups:
      next:
        patterns:
          - "next"
          - "eslint-config-next"
          - "@next/*"
      prisma:
        patterns:
          - "prisma"
          - "@prisma/*"
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
      types:
        patterns:
          - "@types/*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Asia/Jakarta
    open-pull-requests-limit: 3
    labels:
      - "type:chore"
      - "area:devops"
