import { MessageCircleQuestion, Send } from "lucide-react";
import { AppShell } from "@/components/AppShell";
import { PageHeader } from "@/components/PageHeader";
import { ustadzQuestions } from "@/data/mock";

export default function TanyaUstadzPage() {
  return <AppShell active="/tanya-ustadz"><PageHeader eyebrow="Konsultasi Jamaah" title="Tanya Ustadz / Dokter" />
    <section className="mb-6 grid gap-4 lg:grid-cols-[0.9fr_1.1fr]">
      <div className="rounded-[2rem] bg-white p-6 shadow-sm ring-1 ring-slate-100"><div className="mb-4 flex h-12 w-12 items-center justify-center rounded-2xl bg-emerald-50 text-emerald-700"><MessageCircleQuestion className="h-6 w-6" /></div><h2 className="text-2xl font-black text-slate-950">Ajukan Pertanyaan</h2><p className="mt-2 text-sm leading-6 text-slate-600">Prototype form untuk bertanya ke ustadz atau dokter. Nanti akan terhubung ke backend assignment dan moderasi admin.</p><div className="mt-5 space-y-3"><input className="w-full rounded-2xl border border-slate-100 bg-slate-50 px-4 py-3 text-sm outline-none focus:ring-2 focus:ring-emerald-200" placeholder="Judul pertanyaan" /><select className="w-full rounded-2xl border border-slate-100 bg-slate-50 px-4 py-3 text-sm outline-none focus:ring-2 focus:ring-emerald-200"><option>Muamalah</option><option>Ibadah</option><option>Keluarga</option><option>Kesehatan</option></select><textarea className="min-h-32 w-full rounded-2xl border border-slate-100 bg-slate-50 px-4 py-3 text-sm outline-none focus:ring-2 focus:ring-emerald-200" placeholder="Tulis pertanyaan lengkap..." /><button className="flex w-full items-center justify-center gap-2 rounded-2xl bg-emerald-700 px-4 py-3 font-black text-white"><Send className="h-4 w-4" /> Kirim Pertanyaan</button></div></div>
      <div className="rounded-[2rem] bg-gradient-to-r from-emerald-800 to-lime-700 p-6 text-white shadow-lg"><p className="rounded-full bg-white/15 px-4 py-2 text-sm font-semibold inline-flex">Etika bertanya</p><h3 className="mt-4 text-3xl font-black">Gunakan bahasa sopan dan jelaskan konteks.</h3><ul className="mt-5 space-y-3 text-sm text-emerald-50"><li>• Hindari menyebut data pribadi sensitif.</li><li>• Pertanyaan akan dimoderasi admin jika diperlukan.</li><li>• Jawaban bersifat edukasi, bukan fatwa resmi kelembagaan.</li></ul></div>
    </section>
    <section className="rounded-3xl bg-white p-5 shadow-sm ring-1 ring-slate-100"><h3 className="mb-4 text-xl font-black text-slate-950">Pertanyaan Terbaru</h3><div className="space-y-3">{ustadzQuestions.map(item => <article key={item.id} className="rounded-2xl bg-slate-50 p-4"><div className="mb-2 flex flex-wrap items-center justify-between gap-2"><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-700">{item.category}</span><span className={`rounded-full px-3 py-1 text-xs font-bold ${item.status === 'Dijawab' ? 'bg-emerald-100 text-emerald-700' : 'bg-amber-100 text-amber-700'}`}>{item.status}</span></div><h4 className="font-black text-slate-950">{item.question}</h4><p className="mt-2 text-sm leading-6 text-slate-600">{item.answer}</p><p className="mt-3 text-sm font-semibold text-slate-500">{item.ustadz}</p></article>)}</div></section>
  </AppShell>;
}
