import { BookOpen, ChevronRight, Clock3, Package, ShoppingBag, Star } from "lucide-react";
import { campaigns, feeds, orders, products } from "@/data/mock";

export function StatCard({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) { return <div className="rounded-3xl border border-emerald-100/50 bg-white p-4 sm:p-5 shadow-premium hover:shadow-premium-lg transition-all duration-300 hover:-translate-y-1"><div className="mb-4 flex h-12 w-12 items-center justify-center rounded-2xl gradient-emerald text-white shadow-md">{icon}</div><p className="text-sm font-semibold text-slate-500">{label}</p><p className="mt-1 text-2xl font-black text-slate-900 tracking-tight">{value}</p></div>; }
export function ProductCard({ product }: { product: (typeof products)[number] }) { return <div className="group w-[160px] sm:min-w-[240px] shrink-0 rounded-3xl bg-white p-3 sm:p-4 shadow-premium ring-1 ring-emerald-100/50 hover:shadow-premium-lg transition-all duration-300 hover:-translate-y-1"><div className="relative flex h-36 items-center justify-center rounded-2xl bg-gradient-to-br from-emerald-50 via-slate-50 to-emerald-100/50 overflow-hidden"><div className="absolute inset-0 bg-emerald-600/0 group-hover:bg-emerald-600/5 transition-colors" /><span className="absolute left-3 top-3 rounded-xl glass px-3 py-1.5 text-[10px] font-bold uppercase tracking-wider text-emerald-800 shadow-sm">{product.badge}</span><ShoppingBag className="h-14 w-14 text-emerald-600 drop-shadow-sm group-hover:scale-110 transition-transform duration-500" /></div><div className="mt-4 space-y-1.5"><p className="line-clamp-2 font-bold text-slate-900 leading-tight group-hover:text-emerald-700 transition-colors">{product.name}</p><p className="text-xs font-medium text-slate-500">{product.seller}</p><div className="flex items-center justify-between pt-3"><span className="text-lg font-black tracking-tight text-emerald-700">{product.price}</span><span className="flex items-center gap-1 rounded-xl bg-amber-50 px-2 py-1 text-xs font-bold text-amber-700"><Star className="h-3.5 w-3.5 fill-current" /> {product.rating}</span></div></div></div>; }
export function OrderCard({ order }: { order: (typeof orders)[number] }) { return <div className="rounded-3xl border border-emerald-100/50 bg-white shadow-premium p-5 hover:shadow-premium-lg transition-all"><div className="flex items-center justify-between"><p className="font-bold text-slate-900">{order.title}</p><span className="rounded-xl bg-emerald-50 px-3 py-1 text-[10px] font-bold uppercase tracking-wider text-emerald-700">{order.status}</span></div><p className="mt-1 text-sm font-medium text-slate-500">{order.id} • {order.date} • {order.courier}</p><div className="mt-4 h-2.5 rounded-full bg-slate-100 overflow-hidden"><div className="h-full rounded-full gradient-emerald relative" style={{ width: `${order.progress}%` }}><div className="absolute inset-0 bg-white/20" /></div></div><p className="mt-3 text-lg font-black text-slate-900 tracking-tight">{order.amount}</p></div>; }
export function FeedCard({ feed }: { feed: (typeof feeds)[number] }) { return <div className="group flex items-center justify-between rounded-3xl bg-white shadow-premium ring-1 ring-emerald-100/50 p-5 hover:shadow-premium-lg transition-all hover:-translate-y-0.5 cursor-pointer"><div><p className="text-[10px] font-bold uppercase tracking-widest text-emerald-600 mb-1">{feed.type}</p><p className="font-black text-slate-900 text-base sm:text-lg group-hover:text-emerald-700 transition-colors leading-tight">{feed.title}</p><p className="mt-1.5 text-sm font-semibold text-slate-600">{feed.speaker}</p><p className="mt-1 flex items-center gap-1.5 text-xs font-medium text-slate-400"><Clock3 className="h-3.5 w-3.5" /> {feed.time}</p></div><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-emerald-50 text-emerald-600 group-hover:bg-emerald-600 group-hover:text-white transition-colors"><ChevronRight className="h-5 w-5" /></div></div>; }
export function CampaignCard({ campaign }: { campaign: (typeof campaigns)[number] }) { return <section className="relative overflow-hidden rounded-3xl bg-white shadow-premium-lg p-6 sm:p-8 ring-1 ring-emerald-100"><div className="absolute top-0 right-0 w-32 h-32 bg-emerald-50 rounded-full blur-3xl -mr-10 -mt-10" /><div className="relative z-10"><p className="text-[10px] font-bold uppercase tracking-widest text-emerald-600 mb-2">Campaign Pilihan</p><h3 className="text-xl sm:text-2xl font-black text-slate-900 tracking-tight leading-tight">{campaign.title}</h3><p className="mt-3 text-sm font-medium leading-relaxed text-slate-500">Terkumpul <span className="font-bold text-slate-800">{campaign.collected}</span> dari target {campaign.target}</p><div className="mt-5 h-3 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full gradient-emerald relative" style={{ width: `${campaign.percent}%` }}><div className="absolute inset-0 bg-white/20" /></div></div><button className="mt-6 w-full rounded-2xl gradient-emerald shadow-premium hover:shadow-premium-lg hover:scale-[1.02] active:scale-[0.98] transition-all px-4 py-3.5 font-bold text-white text-sm">Donasi Sekarang</button></div></section>; }
export function SectionTitle({ title, icon }: { title: string; icon?: React.ReactNode }) { return <div className="mb-5 flex items-center justify-between"><h3 className="text-xl sm:text-2xl font-black text-slate-900 tracking-tight">{title}</h3>{icon ?? <ChevronRight className="h-5 w-5 text-emerald-700" />}</div>; }
export { BookOpen, Package };
export { EventSlider } from "./EventSlider";
