import { BookOpen, ChevronRight, Clock3, Package, ShoppingBag, Star } from "lucide-react";
import { campaigns, feeds, orders, products } from "@/data/mock";

export function StatCard({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) { return <div className="rounded-3xl border border-emerald-100 bg-white p-3 sm:p-4 shadow-sm"><div className="mb-3 flex h-10 w-10 items-center justify-center rounded-2xl bg-emerald-50 text-emerald-700">{icon}</div><p className="text-sm text-slate-500">{label}</p><p className="mt-1 text-xl font-bold text-slate-900">{value}</p></div>; }
export function ProductCard({ product }: { product: (typeof products)[number] }) { return <div className="w-[160px] sm:min-w-[230px] shrink-0 rounded-3xl bg-white p-3 shadow-sm ring-1 ring-slate-100"><div className="relative flex h-32 items-center justify-center rounded-2xl bg-gradient-to-br from-emerald-100 via-lime-50 to-amber-100"><span className="absolute left-3 top-3 rounded-full bg-white/90 px-3 py-1 text-xs font-semibold text-emerald-700">{product.badge}</span><ShoppingBag className="h-12 w-12 text-emerald-700" /></div><div className="mt-3 space-y-1"><p className="line-clamp-2 font-semibold text-slate-900">{product.name}</p><p className="text-sm text-slate-500">{product.seller}</p><div className="flex items-center justify-between pt-2"><span className="font-bold text-emerald-700">{product.price}</span><span className="flex items-center gap-1 rounded-full bg-amber-50 px-2 py-1 text-xs font-semibold text-amber-700"><Star className="h-3 w-3 fill-current" /> {product.rating}</span></div></div></div>; }
export function OrderCard({ order }: { order: (typeof orders)[number] }) { return <div className="rounded-2xl border border-slate-100 p-4"><div className="flex items-center justify-between"><p className="font-bold text-slate-900">{order.title}</p><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-700">{order.status}</span></div><p className="mt-1 text-sm text-slate-500">{order.id} • {order.date} • {order.courier}</p><div className="mt-3 h-2 rounded-full bg-slate-100"><div className="h-full rounded-full bg-emerald-600" style={{ width: `${order.progress}%` }} /></div><p className="mt-2 font-black text-slate-950">{order.amount}</p></div>; }
export function FeedCard({ feed }: { feed: (typeof feeds)[number] }) { return <div className="flex items-center justify-between rounded-2xl bg-slate-50 p-4"><div><p className="text-xs font-bold uppercase text-emerald-700">{feed.type}</p><p className="mt-1 font-bold text-slate-900">{feed.title}</p><p className="mt-1 text-sm text-slate-500">{feed.speaker}</p><p className="mt-1 flex items-center gap-1 text-sm text-slate-500"><Clock3 className="h-4 w-4" /> {feed.time}</p></div><ChevronRight className="h-5 w-5 text-slate-400" /></div>; }
export function CampaignCard({ campaign }: { campaign: (typeof campaigns)[number] }) { return <section className="rounded-3xl bg-amber-50 p-5 ring-1 ring-amber-100"><p className="text-sm font-bold uppercase text-amber-700">Campaign Aktif</p><h3 className="mt-2 text-xl font-black text-slate-950">{campaign.title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">Terkumpul {campaign.collected} dari target {campaign.target}</p><div className="mt-4 h-3 overflow-hidden rounded-full bg-white"><div className="h-full rounded-full bg-amber-500" style={{ width: `${campaign.percent}%` }} /></div><button className="mt-5 w-full rounded-2xl bg-amber-500 px-4 py-3 font-black text-white">Infaq Sekarang</button></section>; }
export function SectionTitle({ title, icon }: { title: string; icon?: React.ReactNode }) { return <div className="mb-4 flex items-center justify-between"><h3 className="text-xl font-black text-slate-950">{title}</h3>{icon ?? <ChevronRight className="h-5 w-5 text-emerald-700" />}</div>; }
export { BookOpen, Package };
